apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels: {app: fluentd-logzio, tier: monitoring, version: v1}
  name: fluentd-logzio
spec:
  template:
    metadata:
      labels: {name: fluentd-logzio}
    spec:
      containers:
      - env:
        - {name: LOGZIO_URL, value: 'https://listener.logz.io:8071'}
        - name: LOGZIO_TOKEN
          valueFrom:
            secretKeyRef: {key: token, name: logz-io}
        - {name: LOGZIO_TYPE, value: piprekubernetes}
        image: sajid2045/fluentd-kubernetes-logzio:latest
        name: fluentd-logzio
        resources:
          requests: {cpu: 0.15}
        securityContext: {privileged: true}
        volumeMounts:
        - {mountPath: /var/log, name: varlog}
        - {mountPath: /var/lib/docker/containers, name: varlibdockercontainers}
      hostIPC: true
      hostNetwork: true
      hostPID: true
      volumes:
      - hostPath: {path: /var/log}
        name: varlog
      - hostPath: {path: /var/lib/docker/containers, readOnly: true}
        name: varlibdockercontainers
